[project]
name = "steam-game-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zavyalovmaxim", email = "chemezlol228@gmail.com" }
]
requires-python = ">=3.12.6"
dependencies = [
    "boto3>=1.43.62",
    "clickhouse-connect>=1.6.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "tenacity>=9.1.4",
]

[project.scripts]
steam-game-analytics = "steam_game_analytics:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
